numbers=(2,4,3,3,6,4,2,6)
print(numbers)
print("the first element in the tuple is = "+str(numbers[0]))
print("the last element in the tuple is = "+str(numbers[-1]))
print("length of tuple is = "+str(len(numbers)))
names=('john','victor','dom','steve','mark','mack')
print(names)
print("the first element in the tuple is = "+str(names[0]))
print("the last element in the tuple is = "+str(names[-1]))
print("length of tuple is = "+str(len(names)))
